/*
 * fiwix-syscall-off-by-one -- Fiwix's do_syscall bounds check is off by one.
 *
 * Fiwix (kernel/syscalls.c) dispatches a syscall like this:
 *
 *     if (num > NR_SYSCALLS) {          <-- ACCUSED: must be >=, not >
 *         do_bad_syscall(num);
 *         return -ENOSYS;
 *     }
 *     sys_func = syscall_table[num];    <-- one past the table when num == NR_SYSCALLS
 *     if (!sys_func) {                  <-- a NULL check, NOT a bounds check
 *         do_bad_syscall(num);
 *         return -ENOSYS;
 *     }
 *     ... sys_func(...) ...
 *
 * syscall_table has NR_SYSCALLS entries, so its valid indices are
 * 0 .. NR_SYSCALLS-1.  The guard must reject num >= NR_SYSCALLS, but it uses
 * ">", so num == NR_SYSCALLS slips through and syscall_table[NR_SYSCALLS]
 * reads one element PAST the end of the table.  The following if(!sys_func)
 * only turns that into -ENOSYS when the out-of-bounds word happens to be
 * NULL; a non-NULL neighbour is called as a function pointer.
 *
 * This is INDEPENDENT of the LP64 sizeof(unsigned int) count bug (reproducer
 * 07): it is present on stock i386 today, where NR_SYSCALLS already equals
 * the true entry count.
 *
 * The syscall_table body is lifted verbatim from Fiwix v1.5.0 at run time
 * (table.inc, generated by run.sh from the pinned tarball) so the entry
 * count is Fiwix's own.  The accused macro and boundary check below are
 * copied from v1.5.0 and re-grepped against the tarball by run.sh.
 *
 * NR_SYSCALLS unit is selected at compile time:
 *   default            sizeof(unsigned int) -- Fiwix's verbatim macro; on a
 *                       32-bit build (-m32) this equals the entry count, i.e.
 *                       exactly the stock-i386 situation.
 *   -DUSE_POINTER_UNIT sizeof(void *)        -- the count that reproducer 07's
 *                       fix makes correct.  Used on x86_64 so NR_SYSCALLS
 *                       equals the entry count there too, isolating THIS
 *                       off-by-one from the LP64 doubling and letting
 *                       AddressSanitizer trap the one-past read.
 */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "table.inc"   /* generated: sys_* stubs + void *syscall_table[] = { ...v1.5.0 verbatim... } */

#ifdef USE_POINTER_UNIT
#define NR_SYSCALLS	(sizeof(syscall_table) / sizeof(void *))
#else
#define NR_SYSCALLS	(sizeof(syscall_table) / sizeof(unsigned int))	/* Fiwix v1.5.0 verbatim */
#endif

/* the true number of entries -- valid indices are [0, ENTRIES) */
#define ENTRIES		(sizeof(syscall_table) / sizeof(void *))

static void *g_last_fetch;

/*
 * Fiwix do_syscall reduced to its boundary decision.  We perform the fetch
 * syscall_table[num] exactly where Fiwix does (so a real one-past read
 * happens), but we do not jump through a garbage pointer; we hand the
 * decision back so the harness can report it.
 *   0  -> would dispatch syscall_table[num]  (guard passed, entry non-NULL)
 *  -1  -> rejected by the bounds check
 *  -2  -> fetch happened but the !sys_func NULL guard caught it
 */
static int do_syscall_boundary(unsigned int num, int use_fixed_check)
{
	int (*sys_func)(int, ...);
	if (use_fixed_check ? (num >= NR_SYSCALLS) : (num > NR_SYSCALLS)) {	/* ACCUSED: num > NR_SYSCALLS */
		return -1;
	}
	sys_func = (int (*)(int, ...))syscall_table[num];			/* Fiwix: sys_func = syscall_table[num]; */
	g_last_fetch = (void *)sys_func;
	if (!sys_func) {
		return -2;
	}
	return 0;
}

/* forced-adjacency table for the "the NULL guard is not a bounds check" leg:
 * a copy of the real table with a known non-NULL word placed immediately
 * after it, so the one-past fetch is deterministic. */
static int g_poison_called;
static int poison_neighbour(int a, ...) { (void)a; g_poison_called = 1; return 0x5a; }
static struct { void *table[ENTRIES]; void *after; } W;

static int arith_proof(void)
{
	unsigned int n = (unsigned int)NR_SYSCALLS;
	printf(">>> ENTRIES (true slot count)      = %zu\n", (size_t)ENTRIES);
	printf(">>> NR_SYSCALLS (Fiwix macro)      = %u\n", n);
	printf(">>> sizeof(void*)=%zu sizeof(unsigned int)=%zu\n",
	       sizeof(void *), sizeof(unsigned int));
	if ((size_t)NR_SYSCALLS != (size_t)ENTRIES) {
		fprintf(stderr, "FATAL: this build's NR_SYSCALLS (%u) != entry count (%zu);\n"
		        "       run the arith leg only where the unit matches the pointer size\n",
		        n, (size_t)ENTRIES);
		return 1;
	}
	/* the buggy guard admits num == NR_SYSCALLS; the correct guard rejects it */
	if (n > NR_SYSCALLS) { fprintf(stderr, "FATAL: buggy check unexpectedly rejected num==NR_SYSCALLS\n"); return 1; }
	if (!(n >= NR_SYSCALLS)) { fprintf(stderr, "FATAL: correct check failed to reject num==NR_SYSCALLS\n"); return 1; }
	/* and that index is one past the last valid entry */
	if (n != ENTRIES) { fprintf(stderr, "FATAL: NR_SYSCALLS != ENTRIES\n"); return 1; }
	printf(">>> num == NR_SYSCALLS (%u) PASSES `num > NR_SYSCALLS` (admitted)\n", n);
	printf(">>> the correct `num >= NR_SYSCALLS` REJECTS it\n");
	printf(">>> valid indices are 0..%u; index %u is ONE PAST the table\n", n - 1, n);
	printf("RESULT: arith off-by-one PROVEN (num==NR_SYSCALLS dispatches one past)\n");
	return 42;
}

static int oob_read(void)
{
	unsigned int n = (unsigned int)NR_SYSCALLS;
	printf(">>> reading syscall_table[NR_SYSCALLS] = syscall_table[%u] (ENTRIES=%zu)\n",
	       n, (size_t)ENTRIES);
	fflush(stdout);
	/* the real one-past read; under -fsanitize=address this traps */
	int rc = do_syscall_boundary(n, 0);
	printf(">>> fetched %p, boundary rc=%d (no sanitizer trap in this build)\n",
	       g_last_fetch, rc);
	printf("RESULT: oob read completed without a bounds check\n");
	return 0;
}

static int guard_not_a_bound(void)
{
	unsigned int n;
	memcpy(W.table, syscall_table, sizeof(W.table));
	W.after = (void *)&poison_neighbour;	/* the non-NULL word one past W.table */
	n = (unsigned int)ENTRIES;		/* the one-past index */
	void *f = W.table[n];			/* forced-adjacency one-past fetch -> &poison_neighbour */
	printf(">>> W.table[%u] (one past) = %p ; &poison_neighbour = %p\n",
	       n, f, (void *)&poison_neighbour);
	if (f != (void *)&poison_neighbour) {
		fprintf(stderr, "FATAL: forced-adjacency assumption did not hold on this build\n");
		return 1;
	}
	if (!f) { printf("RESULT: guard caught it (neighbour was NULL)\n"); return 1; }
	/* Fiwix's if(!sys_func) passes (f != NULL), so it CALLS the fetched pointer */
	((int (*)(int, ...))f)(0);
	if (!g_poison_called) { fprintf(stderr, "FATAL: out-of-array pointer was not dispatched\n"); return 1; }
	printf(">>> !sys_func was FALSE for an out-of-array pointer -> Fiwix dispatches it\n");
	printf("RESULT: the NULL guard is not a bounds check (out-of-array call reached)\n");
	return 43;
}

static int control_fixed(void)
{
	unsigned int n = (unsigned int)NR_SYSCALLS;
	int rc = do_syscall_boundary(n, 1);	/* the corrected >= check */
	printf(">>> corrected `num >= NR_SYSCALLS` on num==%u -> rc=%d\n", n, rc);
	if (rc != -1) { fprintf(stderr, "FATAL: corrected check did NOT reject the boundary\n"); return 1; }
	printf("RESULT: control OK -- corrected check rejects num==NR_SYSCALLS, no OOB\n");
	return 0;
}

static int control_valid(void)
{
	/* index 1 is sys_exit in Fiwix's table -- a valid, non-NULL entry */
	int rc = do_syscall_boundary(1u, 0);
	printf(">>> valid num=1 -> boundary rc=%d, fetched %p\n", rc, g_last_fetch);
	if (rc != 0) { fprintf(stderr, "FATAL: a valid in-range syscall did not dispatch\n"); return 1; }
	printf("RESULT: control OK -- a valid in-range syscall dispatches normally\n");
	return 0;
}

int main(int argc, char **argv)
{
	if (argc < 2) { fprintf(stderr, "usage: %s <arith|oob|guard|fixed|valid>\n", argv[0]); return 2; }
	if (!strcmp(argv[1], "arith")) return arith_proof();
	if (!strcmp(argv[1], "oob"))   return oob_read();
	if (!strcmp(argv[1], "guard")) return guard_not_a_bound();
	if (!strcmp(argv[1], "fixed")) return control_fixed();
	if (!strcmp(argv[1], "valid")) return control_valid();
	fprintf(stderr, "unknown mode %s\n", argv[1]);
	return 2;
}
