#!/usr/bin/env bash
# fiwix-syscall-off-by-one: Fiwix's do_syscall bounds check is off by one.
# kernel/syscalls.c guards the dispatch with `if(num > NR_SYSCALLS)`, but the
# table's valid indices are 0..NR_SYSCALLS-1, so it must be `>=`.  num ==
# NR_SYSCALLS slips through and syscall_table[NR_SYSCALLS] reads one element
# past the table; the following if(!sys_func) only saves the case where that
# out-of-bounds word happens to be NULL.  Present on stock i386 today and
# INDEPENDENT of the LP64 sizeof(unsigned int) count bug (reproducer 07).
# GREEN == the boundary index is admitted and reads past the table (arithmetic
# proof on i386 and x86_64 + an AddressSanitizer trap), while the corrected
# `>=` check rejects it.
cd "$(dirname "$0")"
. ../common.sh

FIWIX_URL=https://github.com/mikaku/Fiwix/archive/refs/tags/v1.5.0.tar.gz
FIWIX_SHA=e1d5ce53ff6d8648d0411b6a940ad353dcbe82f4c7fc5761e8324fbf2a4c4fe0
SRC=work/Fiwix-1.5.0

mkdir -p work

banner "UPSTREAM RE-CHECK: is the accused boundary still on Fiwix master?"
upstream_still_has "Fiwix master kernel/syscalls.c" \
  "https://raw.githubusercontent.com/mikaku/Fiwix/master/kernel/syscalls.c" \
  "num > NR_SYSCALLS"
# NOTE: Fiwix PR #114 corrected NR_SYSCALLS to count in sizeof(void *) units
# (the LP64 count fix, reproducer 07); that fixes the *count*, not this
# off-by-one.  With a correct count the `num == NR_SYSCALLS` boundary is still
# dispatched one past the table -- on every arch, not just LP64.
upstream_still_has "Fiwix master include/fiwix/syscalls.h" \
  "https://raw.githubusercontent.com/mikaku/Fiwix/master/include/fiwix/syscalls.h" \
  "sizeof(syscall_table) / sizeof(void *)"

banner "FETCH: Fiwix v1.5.0 (github.com/mikaku/Fiwix)"
fetch "$FIWIX_URL" "$FIWIX_SHA" work/fiwix-1.5.0.tar.gz
[ -d "$SRC" ] || tar -xzf work/fiwix-1.5.0.tar.gz -C work

banner "THE ACCUSED CODE (verbatim from the tarball)"
loud "kernel/syscalls.c -- the bounds check, the dispatch, and the NULL guard:"
grep -n 'if(num > NR_SYSCALLS)\|sys_func = syscall_table\[num\]\|if(!sys_func)' "$SRC/kernel/syscalls.c"
loud "include/fiwix/syscalls.h -- NR_SYSCALLS and the table it counts:"
grep -n 'NR_SYSCALLS' "$SRC/include/fiwix/syscalls.h"
grep -n '^void \*syscall_table\[\] = {' "$SRC/kernel/syscalls.c"

banner "verify the harness's accused code is byte-present in v1.5.0"
for needle in 'num > NR_SYSCALLS' 'sys_func = syscall_table[num]'; do
  grep -qF -- "$needle" "$SRC/kernel/syscalls.c" || die "tarball no longer contains: $needle"
  grep -qF -- "$needle" harness.c                || die "harness.c lost the accused string: $needle"
done
grep -qF -- 'sizeof(syscall_table) / sizeof(unsigned int)' "$SRC/include/fiwix/syscalls.h" || die "tarball lost the macro"
grep -qF -- 'sizeof(syscall_table) / sizeof(unsigned int)' harness.c                       || die "harness.c lost the macro"
loud "OK: the boundary check, the dispatch, and the macro all match the tarball"

banner "GENERATE table.inc: Fiwix's real syscall_table + stubs for its entries"
# lift the table body verbatim (its entry count -> our NR_SYSCALLS is Fiwix's own)
awk '/^void \*syscall_table\[\] = {/{f=1} f{print} /^};/{if(f)exit}' \
  "$SRC/kernel/syscalls.c" > work/table_body.c
# one no-op stub per referenced entry name (unused ones, e.g. from a not-taken
# #ifdef branch, are harmless); CONFIG_* left undefined -> #else (NULL) branches
grep -oE '^[[:space:]]*[A-Za-z_][A-Za-z0-9_]*' work/table_body.c \
  | tr -d ' \t' | grep -vE '^(void|NULL|syscall_table)$' | sort -u > work/ids.txt
{
  echo "/* auto-generated by run.sh from Fiwix v1.5.0 -- do not edit */"
  while read -r id; do echo "static int $id(){ return 0; }"; done < work/ids.txt
  cat work/table_body.c
} > work/table.inc
loud "stub count: $(wc -l < work/ids.txt) ; table body lines: $(wc -l < work/table_body.c)"

CC=${CC:-gcc}
CFLAGS="-O0 -g -w -I work"

banner "BUG LEG 1 (stock i386): -m32 build, Fiwix's verbatim sizeof(unsigned int) macro"
loud "on i386 sizeof(unsigned int)==sizeof(void*)==4, so NR_SYSCALLS == entry count"
$CC $CFLAGS -m32 harness.c -o work/h-m32
set +e; ./work/h-m32 arith; rc=$?; set -e
[ $rc -eq 42 ] || die "expected the i386 off-by-one proof (rc 42), got rc $rc"

banner "BUG LEG 1b (x86_64, off-by-one isolated from LP64): sizeof(void*) unit"
loud "using the pointer-size unit reproducer 07's fix installs, so NR_SYSCALLS"
loud "== entry count here too -- the off-by-one stands with a CORRECT count"
$CC $CFLAGS -DUSE_POINTER_UNIT harness.c -o work/h64
set +e; ./work/h64 arith; rc=$?; set -e
[ $rc -eq 42 ] || die "expected the off-by-one proof with a correct count (rc 42), got rc $rc"

banner "BUG LEG 2 (AddressSanitizer): the one-past read is a real OOB"
$CC $CFLAGS -DUSE_POINTER_UNIT -fsanitize=address harness.c -o work/h64-asan
set +e; ./work/h64-asan oob > work/asan.out 2>&1; rc=$?; set -e
cat work/asan.out
if grep -q 'ReserveShadowMemoryRange failed\|failed to allocate' work/asan.out; then
  loud "NOTE: the ASan RUNTIME could not initialize here (address-space ulimit);"
  loud "the one-past read is already proven by legs 1/1b -- not failing over it."
else
  [ $rc -ne 0 ] || die "expected ASan to abort on the one-past read"
  grep -q 'global-buffer-overflow\|heap-buffer-overflow' work/asan.out \
    || die "expected a buffer-overflow report on syscall_table[NR_SYSCALLS]"
  loud "AddressSanitizer confirms: out-of-bounds read at syscall_table[NR_SYSCALLS]"
fi

banner "BUG LEG 3: the if(!sys_func) NULL check is NOT a bounds check"
$CC $CFLAGS -DUSE_POINTER_UNIT harness.c -o work/h64-guard
set +e; ./work/h64-guard guard; rc=$?; set -e
[ $rc -eq 43 ] || die "expected the guard-bypass demonstration (rc 43), got rc $rc"

banner "CONTROL A (red-for-the-right-reason): the corrected >= check rejects it"
set +e; ./work/h64 fixed; rc=$?; set -e
[ $rc -eq 0 ] || die "corrected-check control failed (rc $rc)"

banner "CONTROL B: a valid in-range syscall still dispatches"
set +e; ./work/h64 valid; rc=$?; set -e
[ $rc -eq 0 ] || die "valid-dispatch control failed (rc $rc)"

banner "VERDICT"
loud "BUG REPRODUCED: Fiwix do_syscall admits num == NR_SYSCALLS (\`>\` should be"
loud "\`>=\`), dispatching syscall_table[NR_SYSCALLS] one past the table.  Real on"
loud "stock i386; independent of the LP64 count bug (reproducer 07).  The"
loud "if(!sys_func) guard only helps when the neighbour is NULL."
echo "PASS: fiwix-syscall-off-by-one reproduced"
